### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by kurichii** [kurichii/tabiclip#49]
■ Webアプリの概要
「旅くりっぷ」は、旅行のしおりをWeb上で制作できるサービスです。
スケジュール表に加えて、旅行の写真や持ち物リスト、旅行関連のやることリストなど旅行に関わるさまざまな情報を一元管理することができます。
作成したしおりは旅行参加者と共有したり、本サービス上で公開することができます。
公開設定されたしおりは他のユーザーが閲覧でき、気に入ったしおりはブックマークすることができます。

■ 1週間辺りの開発に向けられる時間
- 1週間あたり：約30時間（2月以降40時間）

■ ProjectsのURL
https://github.com/users/kurichii/projects/2

■ MVPリリースまで
- [ ] ユーザー登録機能
- [ ] ログイン・ログアウト機能
- [ ] 他人が作成したしおり一覧表示機能（未ログインでも閲覧可能）
- [ ] 他人が作成したしおり表示機能（未ログインでも閲覧可能）
- [ ] 他人が作成したしおりのスケジュール表示機能（未ログインでも閲覧可能）
- [ ] 自分が作成したしおり一覧表示機能
- [ ] 自分が作成したしおり表示機能
- [ ] しおり作成機能（画像投稿含む）
- [ ] しおり編集機能（しおりの公開/非公開設定）（画像投稿含む）
- [ ] しおり削除機能
- [ ] スケジュール表表示機能
- [ ] スケジュール登録機能
- [ ] スケジュール詳細表示機能
- [ ] スケジュール編集機能
- [ ] スケジュール削除機能
- [ ] チェックリスト作成機能
- [ ] チェックリスト表示機能
- [ ] チェックリスト編集機能
- [ ] チェックリスト削除機能

■ MVP後
- [ ] しおり共有機能(しおりを参加者にURLで共有するための機能)
- [ ] 立ち寄りスポットのMap表示(Map上にピンを表示)機能
- [ ] チェックリストのリマインダー登録機能(LINEへのプッシュ通知機能)
- [ ] チェックリストのリマインダー解除機能
- [ ] 他人が作成したしおり検索機能（未ログインでも閲覧可能）
- [ ] 他人が作成したしおりのスケジュール表示機能(マップ表示画面)（未ログインでも閲覧可能）
- [ ] パスワードリセット機能
- [ ] プロフィール編集機能
- [ ] 他人が作成したしおりのブックマーク機能
- [ ] ノート作成機能
- [ ] ノート編集機能
- [ ] ノート削除機能
- [ ] アルバム作成機能
- [ ] アルバム編集機能
- [ ] アルバム削除機能
- [ ] SNSログイン（LINEログイン）
- [ ] SNSログイン（Googleログイン）
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] ファビコン
- [ ] 独自ドメイン
- [ ] レスポンシブ対応
- [ ] Xシェア機能
- [ ] OGP（静的）

■ MVPレビュー依頼予定日
予定日：2025年 2月 18日

**Comment by rdhdchloe** [comment]
概ね良いかと思います。LGTMです。

**Comment by kurichii** [comment]
お忙しいところご確認いただきありがとうございます。
見積もり面談の予約させていただきます。
